scrape_configs:
  - job_name: otel-collector
    scrape_interval: 5s
    static_configs:
      - targets: ["otel-collector:8889"]
  - job_name: benchmark-summary
    scrape_interval: 15s
    static_configs:
      - targets: ["benchmark-summary:9100"]
